// Code generated by protoc-gen-go. DO NOT EDIT.
// source: storage.proto

package storagepb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LogType int32

const (
	LogType_TxnLog LogType = 0
)

var LogType_name = map[int32]string{
	0: "TxnLog",
}

var LogType_value = map[string]int32{
	"TxnLog": 0,
}

func (x LogType) String() string {
	return proto.EnumName(LogType_name, int32(x))
}

func (LogType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{0}
}

type TxnCommand_Command int32

const (
	TxnCommand_Set    TxnCommand_Command = 0
	TxnCommand_Delete TxnCommand_Command = 1
)

var TxnCommand_Command_name = map[int32]string{
	0: "Set",
	1: "Delete",
}

var TxnCommand_Command_value = map[string]int32{
	"Set":    0,
	"Delete": 1,
}

func (x TxnCommand_Command) String() string {
	return proto.EnumName(TxnCommand_Command_name, int32(x))
}

func (TxnCommand_Command) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{1, 0}
}

type LogEntry struct {
	Type                 LogType  `protobuf:"varint,1,opt,name=type,proto3,enum=LogType" json:"type,omitempty"`
	LogData              []byte   `protobuf:"bytes,2,opt,name=logData,proto3" json:"logData,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogEntry) Reset()         { *m = LogEntry{} }
func (m *LogEntry) String() string { return proto.CompactTextString(m) }
func (*LogEntry) ProtoMessage()    {}
func (*LogEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{0}
}

func (m *LogEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogEntry.Unmarshal(m, b)
}
func (m *LogEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogEntry.Marshal(b, m, deterministic)
}
func (m *LogEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogEntry.Merge(m, src)
}
func (m *LogEntry) XXX_Size() int {
	return xxx_messageInfo_LogEntry.Size(m)
}
func (m *LogEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_LogEntry.DiscardUnknown(m)
}

var xxx_messageInfo_LogEntry proto.InternalMessageInfo

func (m *LogEntry) GetType() LogType {
	if m != nil {
		return m.Type
	}
	return LogType_TxnLog
}

func (m *LogEntry) GetLogData() []byte {
	if m != nil {
		return m.LogData
	}
	return nil
}

type TxnCommand struct {
	Key                  []byte   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TxnCommand) Reset()         { *m = TxnCommand{} }
func (m *TxnCommand) String() string { return proto.CompactTextString(m) }
func (*TxnCommand) ProtoMessage()    {}
func (*TxnCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{1}
}

func (m *TxnCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxnCommand.Unmarshal(m, b)
}
func (m *TxnCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxnCommand.Marshal(b, m, deterministic)
}
func (m *TxnCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxnCommand.Merge(m, src)
}
func (m *TxnCommand) XXX_Size() int {
	return xxx_messageInfo_TxnCommand.Size(m)
}
func (m *TxnCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_TxnCommand.DiscardUnknown(m)
}

var xxx_messageInfo_TxnCommand proto.InternalMessageInfo

func (m *TxnCommand) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *TxnCommand) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type Timestamp struct {
	Physical             uint64   `protobuf:"varint,1,opt,name=physical,proto3" json:"physical,omitempty"`
	Logical              uint64   `protobuf:"varint,2,opt,name=logical,proto3" json:"logical,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Timestamp) Reset()         { *m = Timestamp{} }
func (m *Timestamp) String() string { return proto.CompactTextString(m) }
func (*Timestamp) ProtoMessage()    {}
func (*Timestamp) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{2}
}

func (m *Timestamp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Timestamp.Unmarshal(m, b)
}
func (m *Timestamp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Timestamp.Marshal(b, m, deterministic)
}
func (m *Timestamp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Timestamp.Merge(m, src)
}
func (m *Timestamp) XXX_Size() int {
	return xxx_messageInfo_Timestamp.Size(m)
}
func (m *Timestamp) XXX_DiscardUnknown() {
	xxx_messageInfo_Timestamp.DiscardUnknown(m)
}

var xxx_messageInfo_Timestamp proto.InternalMessageInfo

func (m *Timestamp) GetPhysical() uint64 {
	if m != nil {
		return m.Physical
	}
	return 0
}

func (m *Timestamp) GetLogical() uint64 {
	if m != nil {
		return m.Logical
	}
	return 0
}

type Txn struct {
	Sequence             uint64        `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Timestamp            *Timestamp    `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Commands             []*TxnCommand `protobuf:"bytes,3,rep,name=commands,proto3" json:"commands,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Txn) Reset()         { *m = Txn{} }
func (m *Txn) String() string { return proto.CompactTextString(m) }
func (*Txn) ProtoMessage()    {}
func (*Txn) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{3}
}

func (m *Txn) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Txn.Unmarshal(m, b)
}
func (m *Txn) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Txn.Marshal(b, m, deterministic)
}
func (m *Txn) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Txn.Merge(m, src)
}
func (m *Txn) XXX_Size() int {
	return xxx_messageInfo_Txn.Size(m)
}
func (m *Txn) XXX_DiscardUnknown() {
	xxx_messageInfo_Txn.DiscardUnknown(m)
}

var xxx_messageInfo_Txn proto.InternalMessageInfo

func (m *Txn) GetSequence() uint64 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

func (m *Txn) GetTimestamp() *Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *Txn) GetCommands() []*TxnCommand {
	if m != nil {
		return m.Commands
	}
	return nil
}

func init() {
	proto.RegisterEnum("LogType", LogType_name, LogType_value)
	proto.RegisterEnum("TxnCommand_Command", TxnCommand_Command_name, TxnCommand_Command_value)
	proto.RegisterType((*LogEntry)(nil), "LogEntry")
	proto.RegisterType((*TxnCommand)(nil), "TxnCommand")
	proto.RegisterType((*Timestamp)(nil), "Timestamp")
	proto.RegisterType((*Txn)(nil), "Txn")
}

func init() { proto.RegisterFile("storage.proto", fileDescriptor_0d2c4ccf1453ffdb) }

var fileDescriptor_0d2c4ccf1453ffdb = []byte{
	// 274 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x90, 0x4f, 0x4f, 0x83, 0x30,
	0x18, 0x87, 0xc7, 0x98, 0x83, 0xbd, 0x4c, 0x43, 0x1a, 0x4d, 0x88, 0x31, 0x86, 0x70, 0x91, 0x78,
	0xe0, 0x80, 0x9f, 0xc0, 0x39, 0x6f, 0x9c, 0x6a, 0x4f, 0xde, 0x3a, 0x7c, 0x83, 0x8b, 0xd0, 0x56,
	0xe8, 0x0c, 0x7c, 0x7b, 0x43, 0x47, 0xd9, 0xad, 0x4f, 0x7f, 0x79, 0xde, 0x7f, 0x70, 0xdd, 0x69,
	0xd9, 0xf2, 0x0a, 0x33, 0xd5, 0x4a, 0x2d, 0x93, 0x1d, 0xf8, 0x85, 0xac, 0xde, 0x85, 0x6e, 0x07,
	0xf2, 0x00, 0x2b, 0x3d, 0x28, 0x8c, 0x9c, 0xd8, 0x49, 0x6f, 0x72, 0x3f, 0x2b, 0x64, 0xc5, 0x06,
	0x85, 0xd4, 0xfc, 0x92, 0x08, 0xbc, 0x5a, 0x56, 0x7b, 0xae, 0x79, 0xb4, 0x8c, 0x9d, 0x74, 0x4b,
	0x2d, 0x26, 0x0c, 0x80, 0xf5, 0xe2, 0x4d, 0x36, 0x0d, 0x17, 0x5f, 0x24, 0x04, 0xf7, 0x07, 0x07,
	0x53, 0x64, 0x4b, 0xc7, 0x27, 0xb9, 0x85, 0xab, 0x3f, 0x5e, 0x9f, 0x70, 0xf2, 0xce, 0x90, 0x3c,
	0x82, 0x67, 0x15, 0x0f, 0xdc, 0x0f, 0xd4, 0xe1, 0x82, 0x00, 0xac, 0xf7, 0x58, 0xa3, 0xc6, 0xd0,
	0x49, 0x5e, 0x61, 0xc3, 0x8e, 0x0d, 0x76, 0x9a, 0x37, 0x8a, 0xdc, 0x83, 0xaf, 0xbe, 0x87, 0xee,
	0x58, 0xf2, 0xda, 0x54, 0x5e, 0xd1, 0x99, 0xa7, 0xc1, 0x4c, 0xb4, 0x34, 0x91, 0xc5, 0x44, 0x83,
	0xcb, 0x7a, 0x31, 0xca, 0x1d, 0xfe, 0x9e, 0x50, 0x94, 0x68, 0x65, 0xcb, 0x24, 0x85, 0x8d, 0xb6,
	0x5d, 0x8c, 0x1e, 0xe4, 0x90, 0xcd, 0x7d, 0xe9, 0x25, 0x24, 0x4f, 0xe0, 0x97, 0xe7, 0x79, 0xbb,
	0xc8, 0x8d, 0xdd, 0x34, 0xc8, 0x83, 0xec, 0xb2, 0x36, 0x9d, 0xc3, 0xe7, 0x3b, 0xf0, 0xa6, 0xcb,
	0x8d, 0xfb, 0xb0, 0x5e, 0x14, 0xb2, 0x0a, 0x17, 0xbb, 0xe0, 0x73, 0x33, 0x9d, 0x5e, 0x1d, 0x0e,
	0x6b, 0x73, 0xfd, 0x97, 0xff, 0x00, 0x00, 0x00, 0xff, 0xff, 0xdb, 0x4c, 0xab, 0x6d, 0x8e, 0x01,
	0x00, 0x00,
}
